Task_1_1_2
MihailCCfit/oop pull request #2
Opened 2022-09-25 15:10 UTC by MihailCCfit

2022-10-03 11:43 UTC, molo4evan requested changes

2022-10-03 11:43 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +    void setSize(int size) {
public? private?

2022-10-03 11:43 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +        datas = (T[]) new Object[1];
Зачем выделять лишний массив, если все равно в setSize создается новый?

2022-10-03 11:43 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +    public final int defaultSize = 5;
Зачем public?

Для внутренней константы - `private static final int DEFAULT_SIZE`

2022-10-03 11:43 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +            datas = (T[]) new Object[1];
Можешь заменить вызовом this()

2022-10-03 11:43 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +    public T[] getDatas() {
Почему datas, а не, например, elements?

2022-10-03 11:43 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +                newArr[i - pointer + len] = datas[i];
arraycopy?

2022-10-03 11:43 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +                datas[i] = null;
Arrays.fill?

2022-10-03 11:43 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +            this.push(ar[i]);
arraycopy?

2022-10-03 13:56 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/Stack.java
> +    void setSize(int size) {
done

2022-10-03 13:57 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/Stack.java
> +        datas = (T[]) new Object[1];
Убрал setSize, т.к. setStize не проверяет на пустоту datas, а базово он пустой.

2022-10-03 13:57 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/Stack.java
> +    public final int defaultSize = 5;
Исправил

2022-10-03 13:57 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/Stack.java
> +            datas = (T[]) new Object[1];
Исправил

2022-10-03 13:57 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/Stack.java
> +    public T[] getDatas() {
Исправил название метода, но datas как-то больше нравилось

2022-10-03 13:57 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/Stack.java
> +                newArr[i - pointer + len] = datas[i];
Исправил

2022-10-03 13:57 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/Stack.java
> +                datas[i] = null;
Исправил

2022-10-03 14:00 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/Stack.java
> +            this.push(ar[i]);
Исправлено

2022-10-08 20:25 UTC, molo4evan requested changes

2022-10-08 20:25 UTC, molo4evan commented on Task_1_2_1/src/main/java/ru/nsu/fit/tsukanov/Stack.java
> +    private static final int defaultSize = 5;
DEFAULT_SIZE

2022-10-08 20:25 UTC, molo4evan commented on Task_1_2_1/src/main/java/ru/nsu/fit/tsukanov/Stack.java
> +     * Add object to stack. ru.nsu.fit.tsukanov.Stack array can be increased by this method.
Тут название пакета уже лишнее)

2022-10-08 20:25 UTC, molo4evan commented on Task_1_2_1/src/main/java/ru/nsu/fit/tsukanov/Stack.java
> +        return "ru.nsu.fit.tsukanov.Stack{"
В toString тоже не обязательно выводить пакет

2022-10-09 05:22 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/ru/nsu/fit/tsukanov/Stack.java
> +    private static final int defaultSize = 5;
done

2022-10-09 05:23 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/ru/nsu/fit/tsukanov/Stack.java
> +     * Add object to stack. ru.nsu.fit.tsukanov.Stack array can be increased by this method.
Согласен, моя ошибка, что проглядел. Исправил.

2022-10-09 05:24 UTC, MihailCCfit commented on Task_1_2_1/src/main/java/ru/nsu/fit/tsukanov/Stack.java
> +        return "ru.nsu.fit.tsukanov.Stack{"
Исправил

2022-10-16 16:15 UTC, molo4evan requested changes
Разреши конфликты для fast-forward merge

И засквошь коммиты в один, пожалуйста, для удобства

2022-10-17 03:12 UTC, merged